---
- hosts: alpine
  remote_user: root

# Before running execute sudo mkdir /root/.ssh && sudo nano /root/.ssh/authorized_keys
# and copy the id_rsa.pub key from the ansible server

  handlers:
  - name: "Restart sshd"
    service:
      name: "sshd"
      state: "restarted"

  tasks:

  - name: Setting hostname
    hostname:
      name: "{{ inventory_hostname }}"

  - name: Changing /etc/hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '^::1'
      line: '::1       {{ inventory_hostname }}'

  - name: install sudo
    apk:
      name: sudo
      state: present
      update_cache: yes

  - name: install bash
    apk:
      name: bash
      state: present
      update_cache: yes

  - name: "Create user accounts"
    user:
      name: "christian"
      state: "present"
      shell: /bin/bash

  - name: "Add authorized keys"
    authorized_key:
      user: "christian"
      key: "{{ lookup('file', '/home/christian/.ssh/id_rsa.pub') }}"

  - name: "Allow admin users to sudo without a password"
    lineinfile:
      dest: "/etc/sudoers"
      state: "present"
      regexp: "^%root"
      insertafter: "^#root"
      line: "christian ALL=(ALL) NOPASSWD: ALL"

  - name: Set the password for the user
    shell:
      cmd: echo christian:christian | chpasswd

  - name: "Disable root login via SSH"
    lineinfile:
      dest: "/etc/ssh/sshd_config"
      regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"
    notify: "Restart sshd"
...
