---
- hosts: alpine
  remote_user: christian
  become: yes
  become_method: sudo

  tasks:

  - name: Update Repositories
    copy:
      src: "{{ lookup('env', 'PWD') }}/support/{{ item }}"
      dest: /etc/apk/repositories
    with_items:
      - 'repositories'

  - name: Update apk cache
    apk:
      update_cache: yes

  - name: Upgrade all apk packages
    apk:
      upgrade: yes

  - name: Install miscellaneous packages with apk
    apk:
      name: "{{ item }}"
      state: present
      update_cache: true
    with_items:
        - neofetch
        - lolcat
        - htop
        - dbus
        - avahi
        - git
        - curl
        - docker
        - docker-compose

  - name: Add to Docker group
    user:
      name: "christian"
      groups: "docker"
      state: "present"

  - name: Starting avahi daemon
    shell:
      cmd: rc-update add avahi-daemon default

  - name: Starting docker service
    shell:
      cmd: rc-update add docker boot

  - name: Reboot the Alpine server
    reboot:
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
