---
- hosts: pi
  remote_user: christian
  become: yes
  become_method: sudo

  tasks:

  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Upgrade all apt packages
    apt: upgrade=dist force_apt_get=yes

  - name: Clean unwanted old stuff
    apt:
      autoremove: yes
      purge: yes

  - name: Install miscellaneous packages with apt
    apt:
      name: "{{ item }}"
      state: present
      update_cache: true
    with_items:
        - screenfetch
        - lolcat
        - ntp

  - name: Remove Swap entry from /etc/fstab.
    lineinfile:
      dest: /etc/fstab
      regexp: swap
      state: absent
    register: task_result

  - name: Set the swap to off
    shell:
      cmd: dphys-swapfile swapoff

  - name: Set the swap to off
    shell:
      cmd: dphys-swapfile uninstall

  - name: Set the swap to off
    shell:
      cmd: update-rc.d dphys-swapfile remove

  - name: Set the swap to off
    shell:
      cmd: systemctl disable dphys-swapfile.service

  - name: Ensure the swap size is 0
    lineinfile:
      path: /etc/dphys-swapfile
      regexp: '^CONF_SWAPSIZE'
      line: CONF_SWAPSIZE=0

  - name: Overclock to 1800GHz
    lineinfile:
      state: present
      insertafter: EOF
      dest: /boot/config.txt
      line: "{{ item }}"
    with_items:
      - 'over_voltage=5'
      - 'arm_freq=1800'
      - 'gpu_freq=750'
    register: task_result

  - name: Expand the file system (RaspberryPi OS)
    shell:
      cmd: raspi-config nonint do_expand_rootfs
    when: task_result is changed

  - name: Reboot the Debian or Ubuntu server
    reboot:
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    when: task_result is changed

  - name: add apt-key for Docker
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: add apt repo for Docker
    apt_repository:
      repo: deb https://download.docker.com/linux/debian buster stable
      state: present
      filename: 'docker'

  - name: install Docker
    apt:
      name: "{{ item }}"
      state: present
      update_cache: true
    with_items:
      - docker-ce
      - docker-compose

  - name: "Add to Docker group"
    user:
      name: "christian"
      groups: "docker"
      state: "present"

  - name: Starting docker service
    systemd:
      name: docker.service
      state: started
      enabled: yes

  - name: Opening Docker Daemon socket for remote access
    lineinfile:
      path: /lib/systemd/system/docker.service
      regexp: '--containerd=/run/containerd/containerd.sock'
      line: 'ExecStart=/usr/bin/dockerd -H fd:// -H=tcp://0.0.0.0:2375 --containerd=/run/containerd/containerd.sock'

  - name: Just force systemd to reread configs
    shell: systemctl daemon-reload

  - name: Reloading docker service
    shell: systemctl restart docker.service

  - name: Download better htop
    get_url:
      url: https://github.com/avafinger/htop_2.2.2/releases/download/v1.8/htop_2.2.2-8_arm64.deb
      dest: /tmp/htop_2.2.2-8_arm64.deb

  - name: Installing better htop
    shell: dpkg -i htop_2.2.2-8_arm64.deb
    args:
      chdir: /tmp/

  - name: Cleaning Up htop
    file:
      path: /tmp/htop_2.2.2-8_arm64.deb
      state: absent

  - name: Creating htop config directory
    become: yes
    become_user: christian
    file:
      path: /home/christian/.config/htop
      state: directory

  - name: Copy htoprc to config directory
    become: yes
    become_user: christian
    copy:
      src: "{{ lookup('env', 'PWD') }}/support/htoprc"
      dest: /home/christian/.config/htop/htoprc
