- hosts: pi
  remote_user: christian
  become: yes
  become_method: sudo
  vars:
    base_dir: /home/christian

  tasks:

  - name: Install bash with apt
    apt:
      name: "{{ item }}"
      state: present
      update_cache: true
    with_items:
      - git
      - curl
      - bash

  - name: Changing shell to bash
    user:
      name: christian
      shell: /bin/bash

  - name: Checking if oh-my-zsh exists
    stat:
      path: "{{ base_dir }}/.oh-my-bash"
    register: OMZ_dir

  - name: Installing oh-my-bash
    become: yes
    become_user: christian
    git:
      repo: git://github.com/ohmybash/oh-my-bash.git
      dest: "{{ base_dir }}/.oh-my-bash"
    when: OMZ_dir.stat.exists == 0

  - name: Copy .bashrc with owner and permission
    become: yes
    become_user: christian
    copy:
      src: "{{ lookup('env', 'PWD') }}/support/{{ item }}"
      dest: "{{ base_dir }}/{{ item }}"
    with_items:
      - '.bashrc'

  - name: Add a better ll command to the aliases
    blockinfile:
      path: "{{ base_dir }}/.oh-my-bash/aliases/ls.aliases.sh"
      marker: "# -- {mark} ANSIBLE MANAGED BLOCK --"
      insertafter: "alias la='ls -Al'               # show hidden"
      block: |
        alias ll='ls -l'                # show hidden files

  - name: Beautify Login process
    lineinfile:
      state: present
      insertafter: EOF
      dest: /home/christian/.profile
      line: "{{ item }}"
    with_items:
        - 'clear && screenfetch | lolcat'
