
- hosts: pi
  remote_user: christian
  become: yes
  become_method: sudo

  tasks:

    - name: add apt-key for telegraf
      apt_key:
        url: https://repos.influxdata.com/influxdb.key
        state: present

    - name: add apt repo for telegraf
      apt_repository:
        repo: deb https://repos.influxdata.com/ubuntu/ focal stable
        state: present
        filename: 'influxdb'

    - name: Install telegraf with apt
      apt:
        name: telegraf
        state: present
        update_cache: true

    - name: Add telegraf to docker and video group
      user:
        name: "telegraf"
        groups: "{{ item }}"
        state: "present"
      with_items:
        - docker
        - video

    - name: Add capabilities to the “ping” 🏓 binary to allow telegraf to execute ping checks
      shell:
        cmd: setcap 'cap_net_admin,cap_net_raw+ep' $(which ping)

    - name: Copy .zshrc, .p10k.zsh and .zprofile with owner and permission
      copy:
        src: "{{ lookup('env', 'PWD') }}/support/{{ item }}"
        dest: "/etc/telegraf/{{ item }}"
      with_items:
        - 'telegraf.conf'

    - name: Reloading telegraf service
      shell:
        cmd: systemctl restart telegraf
