---

- hosts: all
  remote_user: christian
  become: yes
  become_method: sudo

  tasks:

  - name: Uninstalling X11
    apt:
      name: "{{ item }}"
      state: absent
      update_cache: true
    with_items:
      - x11-common
      - bluez
      - gnome-menus
      - gnome-icon-theme
      - gnome-themes-standard
      - hicolor-icon-theme
      - gnome-themes-extra-data
      - bluealsa
      - cifs-utils
      - desktop-base
      - desktop-file-utils

  - name: Cleaning unwanted old stuff
    apt:
      autoremove: yes
      purge: yes

  - name: Updating apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Upgrading all apt packages
    apt: upgrade=dist force_apt_get=yes
    register: task_result

  - name: Rebooting the Debian server
    reboot:
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    when: task_result is changed

  - name: Adding apt-key for docker
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: Adding apt repo for docker
    apt_repository:
      repo: deb https://download.docker.com/linux/debian buster stable
      state: present
      filename: 'docker'
      update_cache: false

  - name: Uncommenting line from /etc/sysctl.conf
    lineinfile:
      dest: /etc/sysctl.conf
      regexp: '^#net.ipv4.ip_forward=1'
      line: 'net.ipv4.ip_forward=1'
    register: task_result

  - name: Switching nftables to iptables
    shell:
      cmd: "{{ item }}"
    loop:
      - update-alternatives --set iptables /usr/sbin/iptables-legacy
      - update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy

  - name: Installing miscellaneous packages
    apt:
      name: "{{ item }}"
      state: present
      update_cache: true
    with_items:
      - screenfetch
      - lolcat
      - ntp
      - apt-transport-https
      - curl
      - gnupg2
      - ca-certificates
      - software-properties-common
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: Adding username to the docker group
    user:
      name: "christian"
      groups: "docker"
      state: "present"

  - name: Copy /etc/docker/daemon.json using symbolic representation
    copy:
      src: "{{ lookup('env', 'PWD') }}/support/daemon.json"
      dest: /etc/docker/daemon.json
      mode: u=rw,g=r,o=r
    register: task_result

  - name: Starting docker service
    systemd:
      name: docker.service
      state: reloaded
      enabled: yes
    when: task_result is changed

  - name: add Kubernetes apt-key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repo for kubernetes
    apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: 'kubernetes'
      update_cache: false

  - name: Installing kubernetes packages
    apt:
      name: "{{ item }}"
      state: present
      update_cache: true
    with_items:
        - kubeadm
        - kubelet

  - name: Starting kubelet service, and enabling it persistently
    service:
     name: kubelet
     enabled: yes

  - name: Rebooting the cluster before deploying kubernetes
    reboot:
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
