- hosts: k8sMasters
  become: yes
  tasks:

    - name: install kubectl
      apt:
        name: kubectl=1.19.0-00
        state: present
        force: yes

    - name: initialize the cluster with standard Flannel subnet
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: christian
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to ansible user home inside kube folder config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/christian/.kube/config
        remote_src: yes
        owner: christian

    - name: install Pod network
      become: yes
      become_user: christian
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> flannel_pod_network_setup.txt
      args:
        chdir: $HOME
        creates: flannel_pod_network_setup.txt
