---
- hosts: all
  remote_user: christian
  become: yes
  become_method: sudo

  tasks:

  - name: Install docker packages with apk
    apk:
      name: "{{ item }}"
      state: present
    with_items:
        - docker
    register: task_result

  - name: "Add to Docker group"
    user:
      name: "christian"
      groups: "docker"
      state: "present"

  - name: Starting docker service
    shell:
      cmd: rc-service docker start

  - name: Copy /etc/docker/daemon.json using symbolic representation
    copy:
      src: "{{ lookup('env', 'PWD') }}/support/daemon.json"
      dest: /etc/docker/daemon.json
      mode: u=rw,g=r,o=r
    register: task_result

  - name: Updating containerd plugin dir
    shell:
      cmd: containerd config default | sed "s|/opt/cni/bin|/usr/libexec/cni|g" > /var/run/docker/containerd/config.toml

  - name: Copy /etc/sysctl.d/99-kubernetes-cri.conf using symbolic representation
    copy:
      src: "{{ lookup('env', 'PWD') }}/support/99-kubernetes-cri.conf"
      dest: /etc/sysctl.d/99-kubernetes-cri.conf
      mode: u=rw,g=r,o=r
    register: task_result

  - name: Setup required sysctl params, these persist across reboots.
    shell:
      cmd: sysctl -p /etc/sysctl.d/99-kubernetes-cri.conf

  - name: Adding docker service to default runlevel
    shell:
      cmd: rc-update add docker default

  - name: Install k8s packages with apk
    apk:
      name: "{{ item }}"
      state: present
    with_items:
        - kubernetes
        - kubelet
        - kubeadm
    register: task_result

  - name: Starting kubelet service
    shell:
      cmd: rc-update add kubelet default

  - name: Prevent conflicts between docker iptables rules and k8s pod communication
    shell:
      cmd: iptables -P FORWARD ACCEPT

  - name: Reboot the Alpine server
    reboot:
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    when: task_result is changed
