---
- hosts: all
  remote_user: christian
  become: yes
  become_method: sudo

  tasks:

  - name: Update apk cache
    apk:
      update_cache: yes

  - name: Upgrade all apk packages
    apk:
      upgrade: yes

  - name: Install Docker packages with apk
    apk:
      name: "{{ item }}"
      state: present
    with_items:
        - docker
    register: task_result

  - name: Add to Docker group
    user:
      name: "christian"
      groups: "docker"
      state: "present"

  - name: Starting docker service
    shell:
      cmd: rc-update add docker default

  - name: Create directory /etc/docker
    file:
      path: /etc/docker
      state: directory

  - name: Copy /etc/docker/daemon.json using symbolic representation
    copy:
      src: "{{ lookup('env', 'PWD') }}/support/daemon.json"
      dest: /etc/docker/daemon.json
      mode: u=rw,g=r,o=r
    register: task_result

  - name: Uncomment line from /etc/sysctl.conf
    lineinfile:
      dest: /etc/sysctl.conf
      state: present
      line: 'net.ipv4.ip_forward=1'
    register: task_result

  - name: Reboot the Alpine server
    reboot:
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    when: task_result is changed

  - name: Install Kubernetes packages with apk
    apk:
      name: "{{ item }}"
      state: present
    with_items:
        - kubelet
        - kubeadm
