- hosts: k8sMasters
  remote_user: christian
  become: yes
  become_method: sudo
  vars:
    base_dir: /home/christian

  tasks:

  - name: Checking if oh-my-bash exists
    stat:
      path: "{{ base_dir }}/.oh-my-bash"
    register: OMZ_dir

  - name: Installing oh-my-bash
    become: yes
    become_user: christian
    git:
      repo: git://github.com/ohmybash/oh-my-bash.git
      dest: "{{ base_dir }}/.oh-my-bash"
    when: OMZ_dir.stat.exists == 0

  - name: Copy .bashrc and .profile with owner and permission
    become: yes
    become_user: christian
    copy:
      src: "{{ lookup('env', 'PWD') }}/support/{{ item }}"
      dest: "{{ base_dir }}/{{ item }}"
    with_items:
      - '.bashrc'
      - '.profile'

  - name: Add a better ll command to the aliases
    blockinfile:
      path: "{{ base_dir }}/.oh-my-bash/aliases/ls.aliases.sh"
      marker: "# -- {mark} ANSIBLE MANAGED BLOCK --"
      insertafter: "alias la='ls -Al'               # show hidden"
      block: |
        alias ll='ls -l'                # show hidden files
