- hosts: all
  remote_user: christian
  become: yes
  become_method: sudo

  tasks:

  - name: Allow all access to tcp port 30001
    community.general.ufw:
      rule: deny
      port: '30001'
      proto: tcp

  - name: Enable ufw
    ufw:
      state: reloaded
